const config = {
  ANUBIS_MQTT_SERVER: process.env.ANUBIS_MQTT_SERVER,
  ANUBIS_MQTT_USERNAME: process.env.ANUBIS_MQTT_USERNAME,
  ANUBIS_MQTT_PASSWORD: process.env.ANUBIS_MQTT_PASSWORD,
  ANUBIS_MQTT_TOPIC: process.env.ANUBIS_MQTT_TOPIC,
  ANUBIS_GPIO_PIN: process.env.ANUBIS_GPIO_PIN
};

export default config;
